RPCApi: RpcApi\__call
__call()
RpcApi::__call ($FunctionName, $Arguments)
Standard service function call.
Parameters
string $FunctionName Name of Remote function to call
array $Arguments If needed the Function arguments
Return values
null|mixed The return value of the called function or null if an Error detected
See also
Call a function or Function arguments
RpcApi::HasError
Api_Call_Example.php
References DEBUG\as_array(), debug(), DEBUG_CALL, DEVICE_CONFIG, ERR_DeviceNotLoaded, and error().