RPCApi: RPCConnection\error
error()
RPCConnection::error ($Message, $ErrorCode = null, $Params = null) protected
Logs an error.
Parameters
int | string $Message Message-number or text to output
int | mixed $ErrorCode ErrorCode or mixed Param to output
mixed $Params Params to replace in Message
Returns
NULL
Demo:
$this->error('This is a simple error'); // logs 'This is a simple error'
$this->error('name %s has error ','The Name'); // logs 'name The Name has error'
$this->error(ERR_FunctionNotFound,'Function Name'); // logs translated id ERR_FunctionNotFound
$this->error('%s and %s are %s its %s',1,2,3,'cool'); // logs '1 and 2 are 3 its cool'
See also
RpcLogger::SetLogOptions
Referenced by decodePacket(), RPCXMLConnection\decodeRequest(), RPCJsonConnection\decodeRequest(), RPCJsonConnection\encodeRequest(), RPCSoapConnection\Execute(), RPCUrlConnection\Execute(), RPCCurlConnection\Execute(), and SendPacket().