RPCApi: RpcConnection\SendPacket
SendPacket()
RpcConnection::SendPacket ($url, $content)
Send packet create with CreatePacket.
Make a plain call to userspezified url. The content must be created by CreatePacket
Parameters
string $url Url to send to
string $content Content to send , created by CreatePacked
Returns
NULL|string the result of call or null if error
References debug(), DEBUG_CALL, DEBUG_DETAIL, decodePacket(), ERR_OpenSoketTo, and error().