RPCApi: IP\Octed
Octed()
IP::Octed ($OctedNumber, $OctedValue = null, $AutoCorrect = false) final
Referenced by OctedFour(), OctedOne(), OctedThree(), and OctedTwo().