RPCApi: RpcLogger\_log
_log()
RpcLogger::_log ($Message, array $Params = null, $AsError = false, $Code = null, $Class = '') private
Logs an message.
Parameters
int | string $Message MessageNumber or Message to output
null | array $Params Params to print out
bool $AsError default=false
null | int $Code the error code. default=null
string $Class the ErrorClass default=''
References DEBUG_ERRORS, doOutput(), and LOG_OPT_SHORT_MESSAGES.
Referenced by Debug(), and Error().