RPCApi: RPCUrlConnection\Execute
Execute()
RPCUrlConnection::Execute ($url, $serviceID, $functionname, array $arguments, array $filter = null)
See also
RPCConnection::Execute()
References RPCConnection\debug(), DEBUG_CALL, UTF8\decode(), ERR_EmptyResponse, RPCConnection\error(), and Filter().