RPCApi: RpcUrlConnection\Execute
Execute()
RpcUrlConnection::Execute ($url, $serviceID, $functionname, array $arguments, array $filter = null)
See also
RpcConnection::Execute()
References RpcConnection\debug(), DEBUG_CALL, UTF8\decode(), ERR_EmptyResponse, RpcConnection\error(), and Filter().