RPCApi: RpcParseEventFromInput
RpcParseEventFromInput()
RpcParseEventFromInput (bool $DoOutput = true)
parse an device event from php://input
Parameters
bool $DoOutput if True sends accept or error back
Returns
string|bool|mixed|null
References RpcParseEvent(), RpcParseSendAccept(), and RpcParseSendError().